### ISSUE TITLE
Does not install default image

### ISSUE THREAD

**Issue by ben-j69** [bitrise-steplib/steps-create-android-emulator#10]
+------------------------------------------------------------------------------+
| (4) create-android-emulator@1.0.0                                            |
+------------------------------------------------------------------------------+
| id: create-android-emulator                                                  |
| version: 1.0.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2016-12-13T10:59:22Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[10:59:22] Start installing (golang) with apt-get       
INFO[10:59:23]  * [OK] Step dependency (go) installed, available. 

Configs:
- Name: avd0
- Platform: android-23
- Abi: armeabi-v7a
- Options: --abi armeabi-v7a
- CustomHardwareProfileContent:
- AndroidHome: /opt/android-sdk-linux

Check if platform installed
installed: true

Check if system image installed
checking path: /opt/android-sdk-linux/system-images/android-23/armeabi-v7a
checking path: /opt/android-sdk-linux/system-images/android-23/default/armeabi-v7a
installed: false

Installing: sys-img-armeabi-v7a-android-23

$ android "update" "sdk" "--no-ui" "--all" "--filter" "sys-img-armeabi-v7a-android-23"

Refresh Sources:
  Fetching https://dl.google.com/android/repository/addons_list-2.xml
  Validate XML
  Parse XML
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl.google.com/android/repository/repository-11.xml
  Validate XML: https://dl.google.com/android/repository/repository-11.xml
  Parse XML:    https://dl.google.com/android/repository/repository-11.xml
  Fetching URL: https://dl.google.com/android/repository/addon.xml
  Validate XML: https://dl.google.com/android/repository/addon.xml
  Parse XML:    https://dl.google.com/android/repository/addon.xml
  Fetching URL: https://dl.google.com/android/repository/glass/addon.xml
  Validate XML: https://dl.google.com/android/repository/glass/addon.xml
  Parse XML:    https://dl.google.com/android/repository/glass/addon.xml
  Fetching URL: https://dl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl.google.com/android/repository/extras/intel/addon.xml
  Parse XML:    https://dl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android/sys-img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/google_apis/sys-img.xml
Warning: The package filter removed all packages. There is nothing to install.
         Please consider trying to update again without a package filter.
checking if system image created at path: /opt/android-sdk-linux/system-images/android-23/armeabi-v7a
checking if system image created at path: /opt/android-sdk-linux/system-images/android-23/default/armeabi-v7a
**system image: sys-img-armeabi-v7a-android-23 not installed**

**Comment by viktorbenei** [comment]
The default image is not android-23 but 19 - you defined android-23 yourself.

Unfortunately the android-23 emulator (the `sys-img-armeabi-v7a-android-23` package) is no longer available, it was removed from the Android packages recently (in the last couple of weeks), so you'll have to use a different emulator version.

Related blog post: http://blog.bitrise.io/2016/11/19/weekly-vm-updates-fastlane-sierra-fix-old-preinstalled-cocoapods-changes.html
