### ISSUE TITLE
The step gives error "Valid ABIs: no ABIs."

### ISSUE THREAD

**Issue by leesah** [bitrise-steplib/steps-create-android-emulator#13]
+------------------------------------------------------------------------------+
    | (7) create-android-emulator@1.1.1                                            |
    +------------------------------------------------------------------------------+
    | id: create-android-emulator                                                  |
    | version: 1.1.1                                                               |
    | collection: https://github.com/bitrise-io/bitrise-steplib.git                |
    | toolkit: go                                                                  |
    | time: 2017-04-22T11:59:02Z                                                   |
    +------------------------------------------------------------------------------+
    |                                                                              |
    INFO[11:59:02] Start installing (golang) with apt-get       
    INFO[11:59:02]  * [OK] Step dependency (go) installed, available. 
    
    Configs:
    - Name: foo
    - Platform: android-25
    - Abi: armeabi-v7a
    - Tag: google_apis
    - Options: 
    - AndroidHome: /opt/android-sdk-linux
    - CustomHardwareProfileContent:
    
    
    Check if platform installed
    installed: true
    
    Check if system image installed
    Checking path: system-images/android-25/google_apis/armeabi-v7a
    installed: true
    
    Creating AVD image
    
    $ /opt/android-sdk-linux/tools/android "create" "avd" "--force" "--name" "foo" "--target" "android-25" "--abi" "armeabi-v7a"
    
    Valid ABIs: no ABIs.
    Failed to create image, error: exit status 1
    |                                                                              |
    +---+---------------------------------------------------------------+----------+
    | x | create-android-emulator@1.1.1 (exit code: 1)                  | 2.97 sec |
    +---+---------------------------------------------------------------+----------+
    | Issue tracker: ...b.com/bitrise-steplib/steps-create-android-emulator/issues |
    | Source: https://github.com/bitrise-steplib/steps-create-android-emulator     |
    +---+---------------------------------------------------------------+----------+

**Comment by godrei** [comment]
Hi @leesah ,
thanks for the issue report!

May i ask you, which stack are you using on bitrise? You can check this on your bitrise app's settings page.

**Comment by leesah** [comment]
It's the Android & Docker, on Ubuntu 16.04 stack. And for what it's worth, the build went fine when I change API level from 25 to 24.

**Comment by trapacska** [comment]
Hey @leesah !

Thank you for the report!
This issue is fixed in this release [1.1.2](https://github.com/bitrise-steplib/steps-create-android-emulator/releases/tag/1.1.2).

Happy Coding! 🎉🚀
