### ISSUE TITLE
Can't create AVD on macOS Sierra/Xamarin stack

### ISSUE THREAD

**Issue by Dids** [bitrise-steplib/steps-create-android-emulator#18]
I've tried both the default and Google APIs tags, but both result in the same error:

```
$ /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/tools/bin/avdmanager "create" "avd" "--force" "--package" "system-images;android-24;google_apis;armeabi-v7a" "--name" "cachedEmulator" "--abi" "armeabi-v7a" "--tag" "google_apis" "--snapshot"

Do you wish to create a custom hardware profile? [no] Error: AVD not created.
null
Failed to create image, error: exit status 1
```

Step:
```
- create-android-emulator:
        run_if: '{{enveq "ANDROID_EMULATOR_EXISTS" "false"}}'
        inputs:
        - name: "$ANDROID_EMULATOR_NAME"
        - platform: android-24
        - tag: google_apis
        - options: "--snapshot"
        - custom_hardware_profile_content: ''
```

Note that I'm also copying over my licenses, if that makes a difference.

**Comment by viktorbenei** [comment]
Thanks for reporting @Dids , we'll check this ASAP!

**Comment by trapacska** [comment]
Hey @Dids !

For now it seems like the issue is coming from the `--snapshot`. Something has changed in the new avdmanager actually, the latest documentation don't even has any words of the snapshot flag: https://developer.android.com/studio/command-line/avdmanager.html

**Comment by testcache** [comment]
The new version of the step ([1.1.4](https://github.com/bitrise-steplib/steps-create-android-emulator/releases/tag/1.1.4)) is released, now it will print verbose messages on errors or warnings. 
Please check if you got something snapshot related error.

**Comment by trapacska** [comment]
The new version of the step is just released ([1.1.4](https://github.com/bitrise-steplib/steps-create-android-emulator/releases/tag/1.1.4)). Now it will print verbose messages of warnings and errors.

Please check if you get some error or warning related to snapshots.

**Comment by Dids** [comment]
@trapacska Just updated and enabled snapshot, same error though. Here's the entire step output:
```
+------------------------------------------------------------------------------+
| (2) create-android-emulator                                                  |
+------------------------------------------------------------------------------+
| id: create-android-emulator                                                  |
| version: 1.1.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-05-23T07:05:29-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[07:05:29]  * [OK] Step dependency (go) installed, available. 

Configs:
- Name: cachedEmulator
- Platform: android-24
- Abi: armeabi-v7a
- Tag: google_apis
- Options: --snapshot
- AndroidHome: /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx
- CustomHardwareProfileContent:


Check if platform installed
installed: true

Check if system image installed
Checking path: system-images/android-24/google_apis/armeabi-v7a
installed: false

Installing system image (platform: android-24 abi: armeabi-v7a tag: google_apis)

$ /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/tools/bin/sdkmanager "system-images;android-24;google_apis;armeabi-v7a"

Warning: File /Users/vagrant/.android/repositories.cfg could not be loaded.
done
Installed

Creating AVD image

Found sdkmanager but no avdmanager, updating SDK Tools...
Warning: File /Users/vagrant/.android/repositories.cfg could not be loaded.
done
- avdmanager successfully installed

$ /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/tools/bin/avdmanager "--verbose" "create" "avd" "--force" "--name" "cachedEmulator" "--abi" "armeabi-v7a" "--package" "system-images;android-24;google_apis;armeabi-v7a" "--tag" "google_apis" "--snapshot"

Do you wish to create a custom hardware profile? [no] Warning: Unable to find a '/Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/tools/lib/emulatorsnapshots.img' file to copy into the AVD folder.
Error: AVD not created.
null
Failed to create image, error: exit status 1
```

**Comment by trapacska** [comment]
There is an extra message now: `Warning: Unable to find a '/Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/tools/lib/emulatorsnapshots.img' file to copy into the AVD folder.`

This warning is seems like entirely wrong. *.img files should not be in `/tools/lib` directory, and the name `emulatorsnapshots.img` is seems to be wrong as well. There is no way currently to do snapshots anyhow. This warning message is coming from Google's `avdmanager`, and I did not found any dependency that should be installed to solve this issue. Like I said, no docs, no posts, nothing about this issue so far.

**Comment by viktorbenei** [comment]
Just my 2 cents, I believe the snapshot flag was removed and if you specify that with the new avdmanager it interprets it as a avd image name/tag flag, not as a command flag; or something along those lines

**Comment by Dids** [comment]
Gotcha, I was more or less following this, so just assumed it was relatively up to date: https://discuss.bitrise.io/t/android-emulator-in-90-seconds/1181

I'll close the issue, since creating the AVD works fine without snapshotting. :)
