### ISSUE TITLE
Failed to install platform, error: exit status 1

### ISSUE THREAD

**Issue by AsifDev21** [bitrise-steplib/steps-create-android-emulator#22]
Check if platform installed
installed: true
Check if system image installed
Checking path: system-images/android-26/default/armeabi-v7a
installed: false
Installing system image (platform: android-26 abi: armeabi-v7a tag: default)
$ /opt/android-sdk-linux/tools/bin/sdkmanager "system-images;android-26;default;armeabi-v7a"
Warning: File /root/.android/repositories.cfg could not be loaded.
Warning: Failed to find package system-images;android-26;default;armeabi-v7a
Failed to install platform, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | **create-android-emulator@1.1.5 (exit code: 1)**                  | 8.90 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...b.com/bitrise-steplib/steps-create-android-emulator/issues |
| Source: https://github.com/bitrise-steplib/steps-create-android-emulator     |

**Comment by viktorbenei** [comment]
There is no 26 "default" image, only Google APIs one, as well as it seems there's no Android 26 ARM emulator, only x86 ones:

```
$ sdkmanager --list --include_obsolete --verbose

...
system-images;android-26;android-tv;x86
    Description:        Android TV Intel x86 Atom System Image
    Version:            4
    Dependencies:
        emulator Revision 26.1.3
system-images;android-26;android-wear;x86
    Description:        Android Wear Intel x86 Atom System Image
    Version:            1
    Dependencies:
        patcher;v4
system-images;android-26;google_apis;x86
    Description:        Google APIs Intel x86 Atom System Image
    Version:            5
    Dependencies:
        emulator Revision 26.1.3
system-images;android-26;google_apis_playstore;x86
    Description:        Google Play Intel x86 Atom System Image
    Version:            5
    Dependencies:
        emulator Revision 26.1.3
...
```

I'd suggest you to use a 24 emulator, that has a non Google APIs version ("default") and ARM emulator.

**Comment by viktorbenei** [comment]
Of course, if you have any questions @AsifDev21 just let us know! ;)
