### ISSUE TITLE
Error preparing SDK package ARM EABI v7a System Image: archive is not a ZIP archive

### ISSUE THREAD

**Issue by abarcelosanchez** [bitrise-steplib/steps-create-android-emulator#26]
Hi!! First of all thanks for this project, it is so helpful for me. I am deploying an android app in bitrise and when I try to create the android emulator I have this error when it tries to download **armeabi-v7a-21_r04.zip**:

```[===========                            ] 30% Downloading armeabi-v7a-21_r04.zip
[============                           ] 33% Downloading armeabi-v7a-21_r04.zip
[============                           ] 33% Downloading armeabi-v7a-21_r04.zip
[============                           ] 33% Unzipping...                      
                                                                                
Warning: An error occurred while preparing SDK package ARM EABI v7a System Image: archive is not a ZIP archive.
[============                           ] 33% Unzipping...
```

This happens sometimes yes and other not. I don't know if change version or what. Thanks in advance!!

**Comment by fehersanyi-bitrise** [comment]
Hello there!

I would recommend changing the method you create the emulator based on this: https://discuss.bitrise.io/t/android-emulator-in-90-seconds/1181/8
the create android emulator is not really dependable. 😢

**Comment by abarcelosanchez** [comment]
Perfect! thank you very much!!!
