### ISSUE TITLE
Unable to target android-20 emulator

### ISSUE THREAD

**Issue by tobrun** [bitrise-steplib/steps-create-android-emulator#4]
As default the value of 19 (4.4.4.) is used for the emualtor creation. 
I tried upgrading this to 20 but I'm now running into:

<img width="712" alt="screen shot 2016-06-19 at 00 54 27" src="https://cloud.githubusercontent.com/assets/2151639/16174208/d0e47f04-35b8-11e6-8e2a-58527785cbf2.png">

**Comment by godrei** [comment]
Hi @tobrun , thanks for reporting.
We are working on the fix.

**Comment by godrei** [comment]
Hi @tobrun,
somehow, there is no `armeabi-v7a` for android api level 20. You can validate it by checking the Android Studio's built in `Android SDK Manager` under `Android 4.4W.2 (API 20)` section or by running `android list sdk --no-ui --all --extended` and searching for `sys-img-armeabi-v7a-android-20`.

By the way the install validation was not correct (in the log you can see sys-img-armeabi-v7a-android-20 installed, but it was not), the step update is in the review phase, it will be released to the steplib tomorrow.

**Comment by tobrun** [comment]
Using another api level resolves it. Closing
