### ISSUE TITLE
How to change abi

### ISSUE THREAD

**Issue by ben-j69** [bitrise-steplib/steps-create-android-emulator#9]
I need to use a google abi but I can't find a way to use the value "google_apis/armeabi-v7a" as abi...

**Comment by viktorbenei** [comment]
Unfortunately Google does not make that easy to install the Google Play API emulators, you have to install more than one package.

You can find our related guide here: http://devcenter.bitrise.io/android/android-tips-and-tricks/#emulator-with-google-apis

We'll close this issue, but if you have any question or issue with the docs, just let us know!
